### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by lipis** [kelp404/Flask-GAE#4]
I have a similar project [gae-init](https://github.com/gae-init) but it has a few more features and a bit different structure.. You could check it out and take some ideas from there.. I might add the closure compiler to my script in the future as well..

You could check the (unfinished) feature list here: 
http://docs.gae-init.appspot.com/features/

If you have any other ideas, they are more than welcome..

**Comment by kelp404** [comment]
Hello @lipis ,

It is cool. :+1: 
Thank you for let me know your project.
