### ISSUE TITLE
No Moduled named Flask

### ISSUE THREAD

**Issue by initNirvana** [kelp404/Flask-GAE#5]
![screenshot 2015-05-20 2 19 11](https://cloud.githubusercontent.com/assets/6625053/7719363/376e6ae6-fefb-11e4-9016-7210733847f5.png)

The local host is running well but not In Google servers.

of course, i tried to appcfg.py update and backend update. changed application name.

**Comment by kelp404** [comment]
```
git submodule update --init
```

**Comment by initNirvana** [comment]
Thank you!
